### ISSUE TITLE
Upgrade to LaxarJS v2

### ISSUE THREAD

**Issue by x1B** [LaxarJS/widget-browser#32]
Upgrade implementation to LaxarJS v2

**Comment by x1B** [comment]
At the same time, use the latest v2.x version of the included widgets (should all be ported by now).

**Comment by jonaswjs** [comment]
Wating for https://github.com/LaxarJS/laxar-developer-tools-widget/issues/65

**Comment by jonaswjs** [comment]
Implemented on `master` (`v2.0.0`).
